name: CMake on a macOS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: macOS-latest
    env:
      WORKDIR: ./macOS

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      working-directory: ${{ env.WORKDIR }}
      run: |
        cmake -S . -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      working-directory: ${{ env.WORKDIR }}
      run: |
        cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
